language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'grunt-i18nlint' ]; then cd .. && eval "mv $currentfolder grunt-i18nlint" && cd grunt-i18nlint; fi

